### ISSUE TITLE
Controlar cuando los métodos de los JPAControllers devuelven false

### ISSUE THREAD

**Issue by oscarfonts** [geomatico/dataportal#12]
Los JPAControllers tienen unos try-catch en todos los métodos, que se están comiendo las excepciones de persistencia.

Si se pasa por el catch, los métodos devuelven false.

Ergo las clases que llaman a estos métodos, deberían comprobar que la respuesta es TRUE, o de lo contrario, informar del error al usuario.

Un ejemplo de dónde habría que intervenir:

> https://github.com/michogar/dataportal/blob/master/query-core/src/main/java/org/dataportal/DownloadController.java#L226

**Comment by michogar** [comment]
Se ha modificado para que en caso de que que se genere una exception en la capa de persistencia, se lance una exception que será controlada en el servlet y se envíe info del error al cliente. No se tiene en cuenta el valor del booleano.
