### ISSUE TITLE
Datos CEAM con time_coverage incoherente

### ISSUE THREAD

**Issue by oscarfonts** [geomatico/dataportal#17]
Atributo time_coverage_start es posterior a time_coverage_end.

Ejemplo:
http://ciclope.cmima.csic.es:8080/thredds/ncml/dataportal/ceam/ES-LMa_FLX_2010_01_12_newformat_ustar.nc

**Comment by fergonco** [comment]
Corregido. Los nuevos .nc de aemet y ceam están aquí: http://www.fergonco.es/files/ceam-aemet.nc.tgz

¿Quién cierra el ticket? ¿el que abre o el que corrige?

**Comment by oscarfonts** [comment]
OK, publicados datos de prueba en:
http://ciclope.cmima.csic.es:8080/thredds/catalog/dataportal/ceam-aemet/

Se puede cerrrar automágicamente el issue en el momento de hacer el commit, añadiendo "closes #17" en el comentario.
