### ISSUE TITLE
Download: cliente no responde a respuesta download del server

### ISSUE THREAD

**Issue by michogar** [geomatico/dataportal#21]
Tras logarse y hacer una búsqueda si le damos a descargar, se descargan los archivos, pero el cliente no muestra nada. La respuesta del server es:

<download>
  <id>0ebcdc7e-1728-4b14-87b7-379a2d36a5a8</id>
  <filename>michogar@gmail.com_20111227135409.zip</filename>
</download>

que se detecta a través de las herramientas de desarrollo de los navegadores

**Comment by oscarfonts** [comment]
Comprobado que se abre cuadro de diálogo en firefox 9, chrome 16, iexplore 8.

Pero tarda un rato; por usabilidad, mostraremos máscara de "waiting...".
