### ISSUE TITLE
Abuso de HttpServletResponse.SC_BAD_REQUEST

### ISSUE THREAD

**Issue by fergonco** [geomatico/dataportal#24]
Los servlets de Login y Locale devuelven un 400 si no se especifican los parámetros correctamente.

El significado de el error 400 no es este. Los servlets deberían devolver un 200 con un código de error a nivel de la aplicación.

No es bloqueante ni importante, sólo incorrecto y me llevó a confusión hasta que me dio por echarle un vistazo al código.

**Comment by oscarfonts** [comment]
No es un comportamiento incorrecto; el significado de HTTP 400 se ajusta a lo que pasa, y es bueno aprovechar la semántica de los estándares establecidos, antes que inventar una solución propia que signifique "bad request".

Sí es incoherente con otros servicios de la aplicación, donde una petición incorrecta se responde con un 200 OK + payload.

Pero de momento se va a quedar así.
