### ISSUE TITLE
Cliente: Formulario de registro no envía petición

### ISSUE THREAD

**Issue by michogar** [geomatico/dataportal#34]
El formulario de registro de usuario no envía ningún tipo de petición. Comprobado desde Chrome.

**Comment by oscarfonts** [comment]
Cliente OK; pero falla servidor al confirmar cambio de contraseña, etc.

**Comment by oscarfonts** [comment]
Repasados los procesos de: Login, Logout, changePass, forgotPass, newUser & tests.
