### ISSUE TITLE
Cliente: el scroll del vocabulario no mueve el arbol de variables

### ISSUE THREAD

**Issue by michogar** [geomatico/dataportal#35]
Al desplegar el arbol de variables aparece el scroll, pero al mover el scroll no se desplaza el arbol por lo que no se puede seleccionar a las variables

**Comment by oscarfonts** [comment]
Overriding buggy extjs 4 scrollbars, using native scrollbars. See:

http://scriptych.hivefire.com/articles/share/104419/
http://stackoverflow.com/questions/7564527/grid-panel-scrollbars-in-extjs-4-not-working
